"""initial schema

Revision ID: 886d16cde5db
Revises:
Create Date: 2026-08-17 10:27:11.412246

This is the project's first migration — there is no prior revision to
build on (``down_revision = None``), so it creates the entire schema from
01-database.md in one file: all 11 tables, every CHECK/UNIQUE/FOREIGN KEY
constraint, and the ``stock_movements`` lookup index.

**What ``upgrade()``/``downgrade()`` are.** Alembic represents each schema
change as a *revision*: a small Python module with two functions.
``upgrade()`` contains the ``op.*`` calls (Alembic's DDL-emitting API —
``op.create_table``, ``op.add_column``, ``op.create_index``, ...) that
move the database *forward* to this revision's shape; ``downgrade()``
contains the calls that undo it, moving back to the previous revision
(here, to nothing — an empty database). ``flask db upgrade`` runs
pending ``upgrade()``s in order; ``flask db downgrade <rev>`` runs
``downgrade()``s in reverse. Alembic tracks "which revision is this
database currently at" in a single-row ``alembic_version`` table it
manages itself.

**What autogenerate did.** ``flask db migrate`` (this file's origin)
didn't write these ``op.*`` calls by hand — it *compared* the live
(empty) database's structure against ``app/models.py``'s
``db.metadata`` (every ``db.Model`` subclass's declared columns/
constraints) and generated the DDL operations needed to close the gap.
That's why this workflow always runs `migrate` against a database that
already reflects the *previous* migration: autogenerate's diff is only
correct relative to whatever schema state it can see.

**Hand-review, then never edit again.** Autogenerate is a diffing tool,
not an oracle — it can miss or mis-render some constructs (see this
project's build notes for the two things fixed here by hand: converting
an unnecessary ``batch_alter_table`` around the composite index into a
plain ``op.create_index``, and confirming every CHECK/UNIQUE/identity/
server_default from 01-database.md actually made it in). Once a
migration like this one has been applied to any real database (dev,
CI, prod), it must never be edited again — editing an already-applied
file rewrites history that some database somewhere has already executed
and recorded in its ``alembic_version`` table, leaving that database's
actual structure and Alembic's on-disk story of how it got there out of
sync in a way no future ``upgrade``/``downgrade`` can reliably repair. A
schema change after this point (01-database.md: "Any later schema change
gets its own migration") always means a brand new revision file, chained
onto this one via its own ``down_revision``.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886d16cde5db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('name', name=op.f('uq_customers_name'))
    )
    op.create_table('parts',
    sa.Column('sku', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('part_type', sa.String(length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), server_default='ea', nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('reorder_point', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("part_type IN ('raw', 'finished')", name=op.f('ck_parts_part_type_valid')),
    sa.CheckConstraint('qty_on_hand >= 0', name=op.f('ck_parts_qty_on_hand_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parts')),
    sa.UniqueConstraint('sku', name=op.f('uq_parts_sku'))
    )
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'operator')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('bom_lines',
    sa.Column('product_part_id', sa.BigInteger(), nullable=False),
    sa.Column('component_part_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_per', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('product_part_id <> component_part_id', name=op.f('ck_bom_lines_product_component_distinct')),
    sa.CheckConstraint('qty_per > 0', name=op.f('ck_bom_lines_qty_per_positive')),
    sa.ForeignKeyConstraint(['component_part_id'], ['parts.id'], name=op.f('fk_bom_lines_component_part_id_parts')),
    sa.ForeignKeyConstraint(['product_part_id'], ['parts.id'], name=op.f('fk_bom_lines_product_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bom_lines')),
    sa.UniqueConstraint('product_part_id', 'component_part_id', name=op.f('uq_bom_lines_product_part_id_component_part_id'))
    )
    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'ordered', 'received', 'canceled')", name=op.f('ck_purchase_orders_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchase_orders_created_by_users')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchase_orders_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders')),
    sa.UniqueConstraint('po_number', name=op.f('uq_purchase_orders_po_number'))
    )
    op.create_table('sales_orders',
    sa.Column('so_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'shipped', 'canceled')", name=op.f('ck_sales_orders_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sales_orders_created_by_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_sales_orders_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_orders')),
    sa.UniqueConstraint('so_number', name=op.f('uq_sales_orders_so_number'))
    )
    op.create_table('stock_movements',
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('qty_delta', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=True),
    sa.Column('ref_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("reason IN ('adjustment', 'wo_consume', 'wo_produce', 'po_receive', 'so_ship')", name=op.f('ck_stock_movements_reason_valid')),
    sa.CheckConstraint("ref_type IS NULL OR ref_type IN ('work_order', 'purchase_order', 'sales_order')", name=op.f('ck_stock_movements_ref_type_valid')),
    sa.CheckConstraint('qty_delta <> 0', name=op.f('ck_stock_movements_qty_delta_nonzero')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_stock_movements_part_id_parts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_stock_movements_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(
        'ix_stock_movements_part_id_created_at',
        'stock_movements',
        ['part_id', sa.literal_column('created_at DESC')],
        unique=False,
    )

    op.create_table('work_orders',
    sa.Column('wo_number', sa.String(length=20), nullable=False),
    sa.Column('product_part_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'released', 'completed', 'canceled')", name=op.f('ck_work_orders_status_valid')),
    sa.CheckConstraint('qty > 0', name=op.f('ck_work_orders_qty_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_work_orders_created_by_users')),
    sa.ForeignKeyConstraint(['product_part_id'], ['parts.id'], name=op.f('fk_work_orders_product_part_id_parts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('wo_number', name=op.f('uq_work_orders_wo_number'))
    )
    op.create_table('po_lines',
    sa.Column('po_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_po_lines_qty_positive')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_po_lines_part_id_parts')),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('fk_po_lines_po_id_purchase_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_po_lines')),
    sa.UniqueConstraint('po_id', 'part_id', name=op.f('uq_po_lines_po_id_part_id'))
    )
    op.create_table('so_lines',
    sa.Column('so_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty > 0', name=op.f('ck_so_lines_qty_positive')),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], name=op.f('fk_so_lines_part_id_parts')),
    sa.ForeignKeyConstraint(['so_id'], ['sales_orders.id'], name=op.f('fk_so_lines_so_id_sales_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_so_lines')),
    sa.UniqueConstraint('so_id', 'part_id', name=op.f('uq_so_lines_so_id_part_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('so_lines')
    op.drop_table('po_lines')
    op.drop_table('work_orders')
    op.drop_index('ix_stock_movements_part_id_created_at', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('sales_orders')
    op.drop_table('purchase_orders')
    op.drop_table('bom_lines')
    op.drop_table('users')
    op.drop_table('suppliers')
    op.drop_table('parts')
    op.drop_table('customers')
    # ### end Alembic commands ###
